clans:
  friendlyFire: true
  killEvent:
    trigger: true
    xpAmount: 0
    players: true
    hostileMobs: true
    peacefulMobs: true
    foreignClanMultiplier: 1.25
  deathEvent:
    trigger: true
    xpAmount: 0
    players: true
    others: false
    foreignClanMultiplier: 1

sessions:
  friendlyFire: true

players:
  streak:
    trigger: true
    resetOnDeath: true
  killEvent:
    trigger: true
    mytharitesAmount: 10
    players: true
    hostileMobs: false
    peacefulMobs: false
    streakMultiplier: 1
  deathEvent:
    trigger: true
    mytharitesAmount: 10
    players: true
    others: false
    streakMultiplier: 1