name: watchdog
version: 0.2.0c-alpha
main: me.u8092.watchdog.Main
author: U8092
website: https://mythmc.ovh/
api-version: '1.20'
commands:
  watchdogreload:
    description: Reload config.yml
    permission: watchdog.reload
    permission-message: You don't have enough permission.
    usage: /<command>