debug: false
debug-prefix: "[MirloDebug]"

variables:
  streak:
    type: int
    scope: player
    default: 0
    increase:
      - PLAYER_KILL_EVENT
    decrease: []
    reset:
      - PLAYER_DEATH_EVENT
  clanFriendlyFire:
    type: boolean
    scope: global
    default: true
    true: []
    false: []
    switch: []
    reset: []
  test:
    type: boolean
    scope: player
    default: false
    true: []
    false: []
    switch: []
    reset: []

channels:
  players:
    send:
      - PLAYER_DEATH_EVENT
      - PLAYER_KILL_EVENT,streak
    receive: []
  clans:
    send:
      - PLAYER_DEATH_EVENT
      - PLAYER_KILL_EVENT
    receive: []
  test:
    send:
      - CREATURE_DEATH_EVENT
      - CREATURE_KILL_EVENT