name: mirlo
version: 0.3.1
main: me.u8092.mirlo.bukkit.MirloBukkitPlugin
author: U8092
website: https://mythmc.ovh/
api-version: '1.20'
commands:
  mirloreload:
    description: Reload config.yml
    permission: mirlo.reload
    permission-message: You don't have enough permissions.
    usage: /<command>